package com.mycompany.tarea1.ut2;

import javax.swing.ButtonModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class NewJFrame2 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame2.class.getName());

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2() {
        initComponents();
        // Esta parte se usa cuando se trabaja con botones.
        sumar.setActionCommand("Sumar");
        restar.setActionCommand("Restar");
        multiplicar.setActionCommand("Multiplicar");
        dividir.setActionCommand("Dividir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        solucion = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        sumar = new javax.swing.JRadioButton();
        restar = new javax.swing.JRadioButton();
        multiplicar = new javax.swing.JRadioButton();
        dividir = new javax.swing.JRadioButton();
        calAuto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(34, 37, 45));

        jLabel4.setText("Resultado:");

        calcular.setText("Calcular");
        calcular.addActionListener(this::calcularActionPerformed);

        solucion.setEditable(false);
        solucion.addActionListener(this::solucionActionPerformed);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(this::limpiarActionPerformed);

        jLabel1.setText("Operaciones:");

        jLabel2.setText("Operador 2:");

        jLabel3.setText("Operador 1:");

        jSpinner1.addChangeListener(this::spinner);

        jSpinner2.addChangeListener(this::spinner);

        buttonGroup2.add(sumar);
        sumar.setText("Sumar");
        sumar.addActionListener(this::operacion);

        buttonGroup2.add(restar);
        restar.setText("Restar");
        restar.addActionListener(this::operacion);

        buttonGroup2.add(multiplicar);
        multiplicar.setText("Multiplicar");
        multiplicar.addActionListener(this::operacion);

        buttonGroup2.add(dividir);
        dividir.setText("Dividir");
        dividir.addActionListener(this::operacion);

        calAuto.setText("Calcular auto");
        calAuto.addActionListener(this::calAutoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multiplicar)
                            .addComponent(restar)
                            .addComponent(dividir)
                            .addComponent(sumar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(solucion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(calcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calAuto)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(sumar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(restar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multiplicar)
                .addGap(3, 3, 3)
                .addComponent(dividir)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(calAuto)
                    .addComponent(limpiar))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(solucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        double operador1 = (Integer) jSpinner1.getValue();
        double operador2 = (Integer) jSpinner2.getValue();

        ButtonModel operador = buttonGroup2.getSelection();
        if(operador == null) {
            solucion.setText("Elige una operación");
            return;
        }
        double sol = Integer.MIN_VALUE;

        /* === 2.0 ===
        switch (operador) {
            case "Sumar":
            sol = operador1 + operador2;
            break;
            case "Restar":
            sol = operador1 - operador2;
            break;
            case "Multiplicar":
            sol = operador1 * operador2;
            break;
            case "Dividir":
            sol = operador1 / operador2;
            break;
        }
         */
        switch (operador.getActionCommand()) {
            case "Sumar":
                sol = operador1 + operador2;
                break;
            case "Restar":
                sol = operador1 - operador2;
                break;
            case "Multiplicar":
                sol = operador1 * operador2;
                break;
            case "Dividir":
                sol = operador1 / operador2;
                break;
        }

        /*
        if (tablaOperaciones.getSelectedIndex() == 0) {
            res = a + b;
        } else if (tablaOperaciones.getSelectedIndex() == 1) {
            res = a - b;
        } else if (tablaOperaciones.getSelectedIndex() == 2) {
            res = a * b;
        } else if (tablaOperaciones.getSelectedIndex() == 3) {
            res = a / b;
        }
         */
        solucion.setText(String.valueOf(sol));
    }//GEN-LAST:event_calcularActionPerformed

    private void solucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solucionActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        buttonGroup2.clearSelection(); // cuando lo hacemos con botones
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        solucion.setText("");
    }//GEN-LAST:event_limpiarActionPerformed
    
    /*===============Calcular de forma automática===============*/
    
    /* === PARTE DE LA OPTIMIZACION, QUITAMOS LOS METODOS DE LAS OPERACIONES ===
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {
        calcularAuto();
    }

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {
        calcularAuto();
    }

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {
        calcularAuto();
    }

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {
        calcularAuto();
    }

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {
        calcularAuto();
    }

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {
        calcularAuto();
    }
    */
    private void calAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calAutoActionPerformed
        // TODO add your handling code here:
        calcularAuto();
    }//GEN-LAST:event_calAutoActionPerformed

    /*=== OPTIMIZACION DE CODIGO PARA USAR LAS 4 OPERACIONES EN SOLO UN MÉTODO ===*/
    private void operacion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacion
        // TODO add your handling code here:
        calcularAuto();
    }//GEN-LAST:event_operacion

    private void spinner(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner
        // TODO add your handling code here:
        calcularAuto();
    }//GEN-LAST:event_spinner
    
    private void calcularAuto(){
        if(calAuto.isSelected()) calcularActionPerformed(null);
    }
    
    /*==================================================================================*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox calAuto;
    private javax.swing.JButton calcular;
    private javax.swing.JRadioButton dividir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton multiplicar;
    private javax.swing.JRadioButton restar;
    private javax.swing.JTextField solucion;
    private javax.swing.JRadioButton sumar;
    // End of variables declaration//GEN-END:variables
}
